### ISSUE TITLE
anotherkrunkerclient: Full Release Feature Tracking

### ISSUE THREAD

**Issue by asger-finding** [asger-finding/anotherkrunkerclient#1]
**Feature exists**: Feature exists in the source, but is not fully implemented.
**Functional**: Feature is fully implemented.
**Full Test Coverage**: Feature is fully functional on all platforms. Tests have been implemented for its API.

---

## Client settings

New tab in the settings popup for anotherkrunkerclient settings specified below.

- [x] Feature Exists
- [x] Functional
- [ ] Full Test Coverage

## Userscript support

Allow users to create scripts with a built-in script editor. JavaScript syntax highlighting.
Create client API with whitelisted API calls for messages and store access.  
Support the [Greasemonkey](https://wiki.greasespot.net/Main_Page) API 

- [x] Feature Exists
- [ ] Functional
- [ ] Full Test Coverage

## discord.js RPC

See [discord-rpc](https://www.npmjs.com/package/discord-rpc)  

Allow user to share their game status on discord with a Rich Presence. Another toggle for sharing game link as well.

- [x] Feature Exists
- [ ] Functional
- [ ] Full Test Coverage

## Custom filter lists

Allow users to apply their own filter lists via a JSON array

- [x] Feature Exists
- [x] Functional
- [ ] Full Test Coverage

## Resource swapper

A normal resource swapper for Krunker. Check files originating from the krunker domain against a folder of the user's choice and redirect the request if it's a match.  
Default path: `%HOMEPATH%/Documents/anotherkrunkerclient`

- [x] Feature Exists
- [x] Functional
- [ ] Full Test Coverage

## Menu Timer

Round countdown in the menu with a toggle in the client settings.

- [ ] Feature Exists
- [ ] Functional
- [ ] Full Test Coverage

## Alt manager

Popup where you can add accounts to quickly switch between. See [LaF](https://github.com/LaFClient/LaF) and [clientpp](https://github.com/6ct/clientpp).

- [ ] Feature Exists
- [ ] Functional
- [ ] Full Test Coverage

## Automatic matchmaking

Joins a match to user preference. (eg. only FFA, specific server target, x amount of players)

- [ ] Feature Exists
- [ ] Functional
- [ ] Full Test Coverage

## Twitch integration

Streamers can have shown their stream chat in the chat box instead of chat messages, and automatically share the !link command for game lobbies with an option for all games and only custom lobbies. Similar to what MTZ client offered.

- [x] Feature Exists
- [x] Functional
- [ ] Full Test Coverage

## Client updating

Check for client updates on splash screen. Don't auto update, but give the user a popup for update when the game launches.  
Use [electron-updater](https://www.npmjs.com/package/electron-updater) for a seamless experience.

- [ ] Feature Exists
- [ ] Functional
- [ ] Full Test Coverage
